<a href="https://colab.research.google.com/github/AI-fanatic24/ASD-DS-AI-ML-Internship/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. A teacher stores the scores of 10 students in a 1D NumPy array. Write code to display the 1D array and print scores greater than 50.

In [ ]:
scores = np.array([60,30,42,55,34,55,66,64,48,55])
print("Scores greater than 50 are:")
print(scores[scores>50])

Scores greater than 50 are:
[60 55 55 66 64 55]


2. Using the same scores array, find the mean score of the class.

In [ ]:
print("Mean of scores:",np.mean(scores))

Mean of scores: 50.9


3. Determine the median of the scores to check the central tendency.

In [ ]:
print("Median of scores:",np.median(scores))

Median of scores: 55.0


4. Find the mode of the scores to identify the most frequent score.

In [ ]:
scores_elements,scores_count = np.unique(scores,return_counts=True)
print("Elements:",scores_elements)
print("Counts:",scores_count)
index = np.where(scores_count == np.max(scores_count))
print(index)
print("Mode of scores:",int(scores_elements[index]))

Elements: [30 34 42 48 55 60 64 66]
Counts: [1 1 1 1 3 1 1 1]
(array([4]),)
Mode of scores: 55


5. You are given a 2D NumPy array containing temperatures recorded over 4 weeks (rows) for 7 days (columns). Display the full array and the temperature of the second week.

In [ ]:
temperature = np.array([
    [32,34,35,38,34,36,39],
    [34,38,40,42,41,38,39],
    [40,41,38,39,40,40,35],
    [36,37,37,38,36,38,39],
])

print(temperature)
print()
print("---Temperature of second week in (degree Celcius)---")
print("\t   ",temperature[1])

[[32 34 35 38 34 36 39]
 [34 38 40 42 41 38 39]
 [40 41 38 39 40 40 35]
 [36 37 37 38 36 38 39]]

---Temperature of second week in (degree Celcius)---
	    [34 38 40 42 41 38 39]


6. Find the highest temperature of the month using NumPy.

In [ ]:
temperature = np.array([34, 41, 35, 33, 42, 37, 43, 31, 38, 36, 34, 40, 39, 44, 32, 41, 35, 43, 30, 44, 42, 33, 41, 38, 34, 45, 36, 41, 37, 43])
print("Highest temperature of the month is",np.max(temperature),"degree Celcius.")

Highest temperature of the month is 45 degree Celcius.


7. Normalize all temperatures using Min-Max normalization formula.

In [ ]:
temperature = np.array([34, 41, 35, 33, 42, 37, 43, 31, 38, 36, 34, 40, 39, 44, 32, 41, 35, 43, 30, 44, 42, 33, 41, 38, 34, 45, 36, 41, 37, 43])
normalized_temperature = (temperature - np.min(temperature)) / (np.max(temperature) - np.min(temperature))
print("Normalized Temperature:")
print(normalized_temperature)

Normalized Temperature:
[0.26666667 0.73333333 0.33333333 0.2        0.8        0.46666667
 0.86666667 0.06666667 0.53333333 0.4        0.26666667 0.66666667
 0.6        0.93333333 0.13333333 0.73333333 0.33333333 0.86666667
 0.         0.93333333 0.8        0.2        0.73333333 0.53333333
 0.26666667 1.         0.4        0.73333333 0.46666667 0.86666667]


8. Calculate the standard deviation of the temperature data.

In [ ]:
temperature = np.array([34, 41, 35, 33, 42, 37, 43, 31, 38, 36, 34, 40, 39, 44, 32, 41, 35, 43, 30, 44, 42, 33, 41, 38, 34, 45, 36, 41, 37, 43])
print("Standard Deviation:",np.std(temperature))

Standard Deviation: 4.25780329382287


9. A supermarket tracks stock of 3 products over 4 weeks and 5 categories. Represent this using a 3D NumPy array. Write code to access stock of 2nd product in week 3.

In [ ]:
'''
ALTERNATIVE:
arr = np.random.randint(5,40,60).reshape(5,3,4)
print(arr)
'''

stocks = np.array([
    [[5,6,8,12],
     [10,22,12,34],
     [15,16,8,11]],

    [[12,43,23,23],
     [14,32,16,7],
     [23,33,12,9]],

    [[44,12,22,18],
     [22,43,18,17],
     [18,16,15,20]],

    [[18,16,22,28],
     [26,24,33,15],
     [11,27,14,26]],

    [[13,22,27,32],
     [32,26,24,33],
     [2,5,4,8]]
])



[23 33 12  9]


In [ ]:
print(stocks[1,2,3])

9


In [ ]:
print("---Stock of second product in week 3 over 5 categories---")
print(stocks[:,1,2])

---Stock of second product in week 3 over 5 categories---
[12 16 18 33 24]


10. Calculate the total stock of each product over all weeks and categories.

In [ ]:
print("Total stock of each product over all weeks and categories:",np.sum(stocks))

Total stock of each product over all weeks and categories: 1159


11. A 1D NumPy array holds survey ratings (scale of 1–10) from 50 people. Find how many people rated more than 7.

In [ ]:
ratings = np.random.randint(1,11,50)
print("---RATINGS---")
print(ratings)
print()
print("Number of people who rated more than 7:",len(ratings[ratings>7]))

---RATINGS---
[ 3  2  5  6  2 10  7  3  3  6  3  3 10  7  8  3  1  7  2  9  6  7 10  6
  6  9  9  6  8  4  1  3  6 10  2  2  9  2  1  9  8 10  9  2  7  9  2 10
  1  4]

Number of people who rated more than 7: 16


12. Count how many people gave a neutral rating (rating == 5).

In [ ]:
print("Number of people who gave a neutral rating (rating == 5):",len(ratings[ratings==5]))

Number of people who gave a neutral rating (rating == 5): 1


13. Normalize the ratings between 0 and 1.

In [ ]:
ratings_normalized = (ratings - np.min(ratings)) / (np.max(ratings) - np.min(ratings))
print("Normalized Ratings:",ratings_normalized)

Normalized Ratings: [0.22222222 0.11111111 0.44444444 0.55555556 0.11111111 1.
 0.66666667 0.22222222 0.22222222 0.55555556 0.22222222 0.22222222
 1.         0.66666667 0.77777778 0.22222222 0.         0.66666667
 0.11111111 0.88888889 0.55555556 0.66666667 1.         0.55555556
 0.55555556 0.88888889 0.88888889 0.55555556 0.77777778 0.33333333
 0.         0.22222222 0.55555556 1.         0.11111111 0.11111111
 0.88888889 0.11111111 0.         0.88888889 0.77777778 1.
 0.88888889 0.11111111 0.66666667 0.88888889 0.11111111 1.
 0.         0.33333333]


14. A fitness app stores 7 days of step count for 5 users in a 2D array. Find the average steps per user.

In [ ]:
steps = np.random.randint(2000,8000,35).reshape(5,7)
print(steps)
print()
print("Average steps per user:",np.round((np.mean(steps,axis=1))))

[[4356 5335 2346 2815 3098 3030 6261]
 [7082 2319 6228 7579 3148 5284 3705]
 [7502 2442 5664 4248 5795 4621 3723]
 [5889 4612 6778 7183 4448 2464 6514]
 [3671 6778 4940 6222 2580 2199 4272]]

Average steps per user: [3892. 5049. 4856. 5413. 4380.]


15. Display the steps recorded on day 3 for all users.

In [ ]:
print("Step count on day-3 for all users:")
print(steps[:,2])

Step count on day-3 for all users:
[2346 6228 5664 6778 4940]


16. Identify users who walked more than 7000 steps on any day.

In [ ]:
c=0
print("Users who walked more than 7000 steps on any day:")
for i in steps:
  for j in i:
    if j>7000:
      print(c+1,end=" ")
      break
  c=c+1

Users who walked more than 7000 steps on any day:
2 3 4 

17. Record the results of 10 trials for 3 chemical samples using a 2D array. Calculate the mean result for each chemical.

In [ ]:
results = np.random.rand(30).reshape(3,10) # rows = chemicals, columns = trials
print(results)
print()
print("Mean for each chemical:",np.mean(results,axis=1))

[[0.09786111 0.30265686 0.65053272 0.67646334 0.6043444  0.31651675
  0.89560856 0.56487896 0.37145222 0.89293653]
 [0.77919229 0.8685219  0.77879215 0.23943039 0.65943071 0.28339471
  0.99534958 0.90224291 0.14010697 0.56030493]
 [0.48485713 0.88049472 0.7988997  0.05450016 0.45943816 0.19995833
  0.31953289 0.21643398 0.1655849  0.94655761]]

Mean for each chemical: [0.53732515 0.62067665 0.45262576]


18. Determine which trial had the highest deviation from the mean for each sample.

In [ ]:
mean = np.mean(results,axis=1)
print(mean)

[0.53732515 0.62067665 0.45262576]


In [ ]:
deviation = mean.reshape(-1,1) - results
print(deviation)

[[ 0.43946404  0.23466828 -0.11320757 -0.13913819 -0.06701925  0.22080839
  -0.35828342 -0.02755382  0.16587292 -0.35561138]
 [-0.15851564 -0.24784525 -0.1581155   0.38124627 -0.03875406  0.33728195
  -0.37467293 -0.28156626  0.48056968  0.06037172]
 [-0.03223137 -0.42786896 -0.34627394  0.3981256  -0.0068124   0.25266742
   0.13309287  0.23619178  0.28704086 -0.49393185]]


In [ ]:
highest_deviation = np.argmax(deviation,axis=1)
print("Trial with highest deviation from mean for each sample:")
for i in range(len(highest_deviation)):
  print("Sample:",i+1,"Trial number:",highest_deviation[i]+1)

Trial with highest deviation from mean for each sample:
Sample: 1 Trial number: 1
Sample: 2 Trial number: 9
Sample: 3 Trial number: 4


19. A hospital records 3 vital signs for 2 patients over 5 days. Store this in a 3D array and retrieve the vitals for the first patient on day 4.

In [ ]:
vitals=np.random.randint(10,100,30).reshape(2,5,3) #block = patient, row = day, column = vital signs
print(vitals)

[[[45 65 37]
  [67 75 41]
  [45 83 67]
  [14 26 27]
  [45 92 99]]

 [[52 95 35]
  [89 31 23]
  [99 22 17]
  [91 28 83]
  [99 74 33]]]


In [ ]:
print("---Vitals of the first patient on day 4---")
print(vitals[0,3,:])

---Vitals of the first patient on day 4---
[14 26 27]


20. Find the mode of a particular vital sign for one patient across all days.

In [ ]:
arr = vitals[1,:,0]
arr_elements,arr_count = np.unique(arr,return_counts=True)
print("Elements:",arr_elements)
print("Counts:",arr_count)
index = np.where(arr_count == np.max(arr_count))
print(index)
print('----------------------------------------------------')
print("Mode of vital-1 for patient number 2 across all days:",int(arr_elements[index]))

Elements: [52 89 91 99]
Counts: [1 1 1 2]
(array([3]),)
----------------------------------------------------
Mode of vital-1 for patient number 2 across all days: 99
